version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - pandoc

sphinx:
  fail_on_warning: true
  configuration: docs/conf.py
  
formats:
  - pdf
  - epub

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
